# Generated by Django 5.1.1 on 2024-09-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia',
            new_name='Clase',
        ),
    ]
