# Generated by Django 5.1.1 on 2024-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_examen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='pr',
            new_name='preguntas_y_respuestas',
        ),
        migrations.AddField(
            model_name='examen',
            name='nombre',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='num_preguntas',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
