# Generated by Django 5.1.1 on 2024-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_rename_pr_examen_preguntas_y_respuestas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='pags',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
