# Generated by Django 5.1.1 on 2024-09-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_examen_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='clase',
        ),
    ]
