# Generated by Django 5.1.1 on 2024-09-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_examen_lase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='lase',
            new_name='clase',
        ),
    ]
