# Generated by Django 5.1.1 on 2024-09-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0015_examen_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calificaciones', models.TextField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='miapp.clase')),
            ],
        ),
    ]
