# Generated by Django 5.1.1 on 2024-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0016_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='matricula',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
